### ISSUE TITLE
Did this whole project stop

### ISSUE THREAD

**Issue by floriankri** [Interbotix/HROS1-Framework#26]
Since the last commit happened 2 years ago, I wanted to know wether or not the whole project was just shut down?

**Comment by HonkStonk** [comment]
I wonder the same. Hope it’s still active somewhere else?

**Comment by floriankri** [comment]
@HonkStonk I really don't know I the project is still active, but nevertheless we could connect and try some things together.

**Comment by sarendt** [comment]
My robotics team and makerspace are looking at building one of these as well.  Were interested in helping if anyone starts workin on this again.
